import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title='Cherry Calculator', layout='centered')

st.markdown("<style>header, footer, #MainMenu{visibility:hidden;}.block-container{padding:0; max-width:480px;}[data-testid='stAppViewContainer']{background: linear-gradient(180deg, #e68f82 0%, #f9d9d2 100%);}</style>", unsafe_allow_html=True)

html_code = (
"<div class='outer'><div class='calc'>"
"<div class='top'><div class='top-icons'>"
"<span class='t-icon' id='funcBtn'>√x</span>"
"<span class='t-icon' id='histBtn'>↻</span>"
"</div></div>"
"<div class='display' id='display'>0</div>"
"<div class='slide-panel' id='funcPanel'>"
"<div class='slide-head'><b>Functions</b><span class='close' onclick='closePanels()'>X</span></div>"
"<div class='f-grid'>"
"<button onclick=\"doFunc('INV')\" id='invBtn'>INV</button>"
"<button onclick=\"doFunc('RAD')\" id='radBtn'>RAD</button>"
"<button onclick=\"insert('%')\">%</button>"
"<button onclick=\"insertTrig('sin')\">sin</button>"
"<button onclick=\"insertTrig('cos')\">cos</button>"
"<button onclick=\"insertTrig('tan')\">tan</button>"
"<button onclick=\"insertF('ln')\">ln</button>"
"<button onclick=\"insertF('log')\">log</button>"
"<button onclick=\"insert('!')\">!</button>"
"<button onclick=\"insert('pi')\">π</button>"
"<button onclick=\"insert('e')\">e</button>"
"<button onclick=\"insert('^')\">^</button>"
"<button onclick=\"insert('(')\">(</button>"
"<button onclick=\"insert(')')\">)</button>"
"<button onclick=\"insertF('sqrt')\">√</button>"
"</div></div>"
"<div class='slide-panel' id='histPanel'>"
"<div class='slide-head'><b>History</b><span class='close' onclick='clearHist()'>Clear</span><span class='close' onclick='closePanels()'>X</span></div>"
"<div id='hList' class='h-list'>No history</div>"
"</div>"
"<div class='grid'>"
"<button onclick='clearAll()'>C</button>"
"<button onclick=\"insert('/')\">÷</button>"
"<button onclick=\"insert('*')\">×</button>"
"<button onclick='back()'>⌫</button>"
"<button onclick=\"insert('7')\">7</button>"
"<button onclick=\"insert('8')\">8</button>"
"<button onclick=\"insert('9')\">9</button>"
"<button onclick=\"insert('-')\">−</button>"
"<button onclick=\"insert('4')\">4</button>"
"<button onclick=\"insert('5')\">5</button>"
"<button onclick=\"insert('6')\">6</button>"
"<button onclick=\"insert('+')\">+</button>"
"<button onclick=\"insert('1')\">1</button>"
"<button onclick=\"insert('2')\">2</button>"
"<button onclick=\"insert('3')\">3</button>"
"<button class='eq' onclick='calc()'>=</button>"
"<button onclick=\"insert('%')\">%</button>"
"<button onclick=\"insert('0')\">0</button>"
"<button onclick=\"insert('.')\">.</button>"
"</div></div></div>"
"<style>"
".outer{display:flex;justify-content:center;align-items:center;height:94vh;}"
".calc{width:285px;height:560px;background:#fff8f4;border:2.5px solid #8c1e2f;border-radius:24px;padding:32px 14px 10px 14px;display:flex;flex-direction:column;position:relative;}"
".top{height:32px;display:flex;justify-content:flex-end;align-items:flex-start;padding-top:10px;padding-bottom:14px;}"
".top-icons{display:flex;gap:18px;margin-right:6px;}"
".t-icon{font-size:15px;color:#8c1e2f;cursor:pointer;}"
".display{height:90px;font-size:56px;font-weight:300;text-align:right;color:#111;padding-right:8px;display:flex;justify-content:flex-end;align-items:center;margin-bottom:6px;}"
".grid{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;grid-template-rows:repeat(5, 66px);gap:5px;flex:1;}"
".grid button{background:transparent;border:none;font-size:19px;color:#4a2a2a;border-radius:12px;cursor:pointer;}"
".grid button:hover{background:#ffe8e1;}"
".eq{grid-column:4;grid-row:4 / span 2;background:#c21f35!important;color:white!important;border-radius:18px!important;font-size:26px!important;}"
".slide-panel{position:absolute;top:52px;left:10px;right:10px;bottom:14px;background:#fff8f4;border:2px solid #8c1e2f;border-radius:16px;padding:12px;z-index:20;display:none;}"
".slide-panel.open{display:block;}"
".slide-head{display:flex;justify-content:space-between;color:#8c1e2f;font-size:13px;margin-bottom:10px;}"
".close{cursor:pointer;margin-left:10px;}"
".f-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;}"
".f-grid button{background:#ffeae5;border:1px solid #eab0a6;border-radius:9px;padding:9px 0;}"
".h-list{font-size:13px;line-height:1.8;max-height:400px;overflow-y:auto;}"
"</style>"
"<script>"
"let expr='';let isRad=true;let isInv=false;let hist=[];const disp=document.getElementById('display');"
"function upd(){disp.innerText=expr||'0';}"
"function insert(v){if(v=='pi'){expr+='3.1415926535';upd();return;}if(v=='e'){expr+='2.7182818284';upd();return;}expr+=v;upd();}"
"function insertF(f){if(f=='sqrt')expr+='Math.sqrt(';if(f=='ln')expr+='Math.log(';if(f=='log')expr+='Math.log10(';upd();}"
"function insertTrig(t){expr+=(isInv?'a':'')+t+'(';upd();}"
"function doFunc(f){if(f=='INV'){isInv=!isInv;let b=document.getElementById('invBtn');b.style.background=isInv?'#8c1e2f':'';b.style.color=isInv?'white':'';}if(f=='RAD'){isRad=!isRad;document.getElementById('radBtn').innerText=isRad?'RAD':'DEG';}}"
"function clearAll(){expr='';upd();}function back(){expr=expr.slice(0,-1);upd();}"
"function closePanels(){document.getElementById('funcPanel').classList.remove('open');document.getElementById('histPanel').classList.remove('open');}"
"function fact(n){let r=1;for(let i=2;i<=n;i++)r*=i;return r;}"
"function calc(){try{let e=expr;if(!e)return;e=e.replace(/(\\d+\\.?\\d*)%/g,'($1/100)').replace(/(\\d+)!/g,function(_,n){return fact(parseInt(n));}).replace(/\\^/g,'**');let ang=function(x){return isRad?x:x*Math.PI/180;};let iang=function(x){return isRad?x:x*180/Math.PI;};let _asin=function(x){return iang(Math.asin(x));};let _acos=function(x){return iang(Math.acos(x));};let _atan=function(x){return iang(Math.atan(x));};e=e.replace(/asin\\(/g,'_asin(').replace(/acos\\(/g,'_acos(').replace(/atan\\(/g,'_atan(').replace(/sin\\(/g,'Math.sin(ang(').replace(/cos\\(/g,'Math.cos(ang(').replace(/tan\\(/g,'Math.tan(ang(');let res=eval(e);res=parseFloat(Number(res).toFixed(10)).toString();hist.unshift(expr+' = '+res);renderH();expr=res;upd();}catch(err){disp.innerText='Error';expr='';}}"
"function renderH(){let l=document.getElementById('hList');l.innerHTML=hist.length?hist.map(function(h){return '<div style=\"border-bottom:1px dashed #eab0a6;padding:4px 0\">'+h+'</div>';}).join(''):'No history';}"
"function clearHist(){hist=[];renderH();}"
"document.getElementById('funcBtn').onclick=function(){let p=document.getElementById('funcPanel');let h=document.getElementById('histPanel');h.classList.remove('open');p.classList.toggle('open');};"
"document.getElementById('histBtn').onclick=function(){let p=document.getElementById('funcPanel');let h=document.getElementById('histPanel');p.classList.remove('open');h.classList.toggle('open');renderH();};"
"</script>"
)

components.html(''.join(html_code), height=680, scrolling=False)